//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholl_management_WebApplicationmodel.Dbconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answers()
        {
            this.Answers1 = new HashSet<Answers>();
        }
    
        public int Id { get; set; }
        public Nullable<int> questionId { get; set; }
        public string title { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> isCorrect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answers> Answers1 { get; set; }
        public virtual Answers Answers2 { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
