//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholl_management_WebApplicationmodel.Dbconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int Id { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CountryName { get; set; }
        public Nullable<int> StateName { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual States States { get; set; }
    }
}
