//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholl_management_WebApplicationmodel.Dbconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupen
    {
        public int id { get; set; }
        public string Coupencode { get; set; }
        public Nullable<int> Percentages { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
    }
}
