//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scholl_management_WebApplicationmodel.Dbconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderId { get; set; }
        public Nullable<int> ProductName { get; set; }
        public Nullable<int> Qtn { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Producttable Producttable { get; set; }
    }
}
